services:
  blog:
    build: .
    container_name: blog
    restart: unless-stopped
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    depends_on:
      blog-db:
        condition: service_healthy
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python /code/manage.py runserver 0.0.0.0:8000

  blog-db:
    image: postgres:14
    container_name: blog-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
