# Generated by Django 5.1.5 on 2025-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(
                default='This is where the description would have gone.', max_length=210),
            preserve_default=False,
        ),
    ]
