# Generated by Django 5.1.5 on 2025-01-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='No alt text given because I only think about myself.', max_length=500),
        ),
    ]
